language: node_js
node_js:
  - 4.0
  - 5.0
services:
  - mysql
before_script:
  - mysql < assets/mysql-test.sql
env:
  - NODE_ENV=development MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_USER=root MYSQL_PASSWORD= MYSQL_DATABASE=naomi_test
